### ISSUE TITLE
Smart support for LEDs on Field etc.

### ISSUE THREAD

**Issue by grrrwaaa** [grrrwaaa/oopsy#1]
Field has 24 LEDs. It doesn't make sense at all to have these use an [out] for each one. Some kind of stream multiplexing or binary coding is probably wanted here, so a single [out] can drive them all.

**Comment by grrrwaaa** [comment]
Had the idea of using a [data leds 24] as a way to address this. Or a 3-channel [data leds 24 3] for RGB values.

**Comment by stephenhensley** [comment]
oh -- worth mentioning, unlike the Petal and Pod boards the LEDs on the field are all single color. 

so that may actually simplify this a bit.

**Comment by grrrwaaa** [comment]
Field leds are now addressable via [data leds 24].  Needed a little hack to reverse the ordering of B1-B8 to be more intuitive, but seems to be working very smoothly.
